export { default as SignUp } from './signup'
export { default as Login } from './login'
export { default as About } from './about'
export { default as NewArticle } from './articles/new-article'
export { default as ArticleList } from './articles/article-list'
export { default as Article } from './articles/article'
export { default as NotFound } from './error/not-found'
export { default as AdminDashboard } from './admin/dashboard'
